category/urls.py
from django.urls import path

from category import views
from category.apps import CategoryConfig

app_name = CategoryConfig.name

urlpatterns = [
    path("", views.CategoryListView.as_view(), name='list'),
    path("<int:pk>/", views.CategoryDetailView.as_view(), name='detail'),
    path("create/", views.CategoryCreateView.as_view(), name='create'),
    path("edit/<int:pk>/", views.CategoryUpdateView.as_view(), name='update'),
    path("delete/<int:pk>/", views.CategoryDeleteView.as_view(), name='delete'),

    path("crib/", views.CribListView.as_view(), name='crib-list'),
    path("cat-crib/<int:pk>/", views.CatCribListView.as_view(), name='cat-crib-list'),
    path("crib/<int:pk>/", views.CribDetailView.as_view(), name='crib-detail'),
    path("crib/create/", views.CribCreateView.as_view(), name='crib-create'),
    path("crib/create/<int:pk>/", views.CatCribCreateView.as_view(), name='cat-crib-create'),
    path("crib/edit/<int:pk>/", views.CribUpdateView.as_view(), name='crib-update'),
    path("crib/delete/<int:pk>/", views.CribDeleteView.as_view(), name='crib-delete'),

]

cribs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('category.urls', namespace = 'category'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True, blank=False, null=False, verbose_name='название')
    description = models.CharField(max_length=2000, verbose_name='описание', **NULLABLE)
    preview = models.ImageField(upload_to='category/', verbose_name='превью', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Crib(models.Model):
    name = models.CharField(max_length=200, unique=True, blank=False, null=False, verbose_name='название')
    description = models.CharField(max_length=2000, verbose_name='описание', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'шпора'
        verbose_name_plural = 'шпоры'
        ordering = ('name',)

category/forms.py
from django import forms

from category.models import Category, Crib


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description', 'preview']

category/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from category.forms import CategoryForm
from category.models import Category, Crib


# Create your views here.
class CategoryListView(ListView):
    model = Category
    paginate_by = 12


class CategoryDetailView(DetailView):
    model = Category


class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('category:list')


class CategoryCreateView(CreateView):
    model = Category
    fields = ('name', 'description', 'preview')
    success_url = reverse_lazy('category:list')


class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('category:list')

    def post(self, request, *args, **kwargs):
        if request.user.is_superuser:
            super().post(request, *args, **kwargs)
        return redirect(self.success_url)


class CribListView(ListView):
    model = Crib


class CribDetailView(DetailView):
    model = Crib


class CribCreateView(CreateView):
    model = Crib
    fields = ('name', 'description', 'category')
    success_url = reverse_lazy('category:list')


class CribUpdateView(UpdateView):
    model = Crib
    fields = ('name', 'description', 'category')
    success_url = reverse_lazy('category:list')


class CribDeleteView(DeleteView):
    model = Crib
    success_url = reverse_lazy('category:list')


class CatCribCreateView(CreateView):
    model = Crib
    fields = ('name', 'description', 'category')
    success_url = reverse_lazy('category:list')

    def get(self, request, *args, **kwargs):
        pk = kwargs["pk"]
        if pk:
            cat = Category.objects.filter(pk=pk).first()
            self.initial.update({'category': cat})
        return super().get(request, *args, **kwargs)


class CatCribListView(ListView):
    model = Crib

    def get_queryset(self):  # переопределяем получение объектов
        pk = self.kwargs.get('pk', None)  # получаем аргумент из ссылки
        if pk is not None:  # если аргумент существует
            self.object = Category.objects.filter(pk=pk).first()
            return Crib.objects.filter(category_id__exact=pk)  # фильтруем по нему посты
        return Crib.objects.all()

category/templates/category/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    <title>Шпаргалки</title>
</head>
<body>

<div class="container">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'category:list' %}">Категории</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'category:create' %}">Добавить категорию</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'category:crib-create' %}">Добавить шпаргалку</a>
        </li>
    </ul>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

category/templates/category/category_confirm_delete.html
{% include 'category/base.html' %}

{% block content %}
<div class="card border-0 align-items-center">

        <div class="card w-25 mt-4 ml-3">

            <form method="post">
                {% csrf_token %}
                <div class="card-header">
                    Вы уверены, что хотите удалить категорию {{ object.name }} со всеми её шпаргалками?
                </div>
                <div class="card-body">
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a href="{% url 'category:list' %}">Отмена</a>
                </div>
            </form>
            </div>

</div>


{% endblock %}

category/templates/category/category_detail.html
{% include 'category/base.html' %}
{% block content %}
    <div class="row mt-4 ml-3 mr-3">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-2">
                    <img src="/media/{{ object.preview }}" class="img-fluid rounded-start" alt="логотип">
                </div>
                <div class="col-md-10">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.name }}</h5>
                        <p class="card-text">{{ object.description }}</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
<hr>

{% endblock %}

category/templates/category/category_form.html
{% include 'category/base.html' %}

{% block content %}
    <div class="row ml-3 mr-3 mt-4">
        <div class="card">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'category:list' %}">Отмена</a>
            </form>
        </div>
    </div>
{% endblock %}

category/templates/category/category_list.html
{% include 'category/base.html' %}

{% block content %}

    <div class="row ml-3 mr-3 mt-4">
        {% for item in object_list %}
            <div class="col-3 mb-2">
                <div class="card">
                    <div class="row">
                    <div class="col">
                        {% if item.preview %}
                        <img class="card-img-top" style="height: 100px;width: 150px;" src="/media/{{ item.preview }}" alt="логотип">
                        {% else %}
                        <img class="card-img-top" style="height: 100px;width: 150px;" src="/media/category/logogo.jpg" alt="логотип">
                        {% endif %}
                    </div>
                    <div class="col">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url 'category:cat-crib-list' item.pk %}">{{ item.name }}</a>
                            </h5>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                       href="{% url 'category:list' %}?page={{ page_obj.previous_page_number }}">Назад</a>
                </li>
            {% endif %}
            {% if page_obj.has_previous or page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"> {{ page_obj.number }} / {{ page_obj.paginator.count }}</a>
                </li>
            {% endif %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                       href="{% url 'category:list' %}?page={{ page_obj.next_page_number }}">Вперед</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

category/templates/category/crib_confirm_delete.html
{% include 'category/base.html' %}

{% block content %}
<div class="card border-0 align-items-center">

        <div class="card w-25 mt-4 ml-3">

            <form method="post">
                {% csrf_token %}
                <div class="card-header">
                    Вы уверены, что хотите удалить {{ object.name }}?
                </div>
                <div class="card-body">
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a href="{% url 'category:list' %}">Отмена</a>
                </div>
            </form>
            </div>

</div>


{% endblock %}

category/templates/category/crib_detail.html
{% include 'category/base.html' %}

{% block content %}
    <div class="row-10 ml-3 mr-3 mt-4">
        <div class="card">

            <div class="card-header">
                {{ object.name }}
                (<a href="{% url 'category:cat-crib-list' object.category.pk %}" >{{ object.category.name }}</a>)
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{ object.description }}</p>
                </blockquote>
            </div>
            <div class="row ml-3 mb-3">

                <a href="{% url 'category:crib-update' object.pk %}" class="btn btn-primary mr-3">изменить</a>

                <a href="{% url 'category:crib-delete' object.pk %}" class="btn btn-primary">удалить</a>

            </div>

        </div>
    </div>
    <hr>

{% endblock %}

category/templates/category/crib_form.html
{% include 'category/base.html' %}

{% block content %}
    <div class="row ml-3 mr-3 mt-4">
        <div class="card">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'category:list' %}">Отмена</a>
            </form>
        </div>
    </div>
{% endblock %}

category/templates/category/crib_list.html
{% include 'category/base.html' %}
{% block content %}
    <div class="row mt-4 ml-3 mr-3">
        <div class="card mb-3">
            <div class="row">
                <div class="col">
                    {% if view.object.preview %}
                        <img class="card-img-top" style="height: 100px;width: 150px;"
                             src="/media/{{ view.object.preview }}" alt="логотип">
                    {% else %}
                        <img class="card-img-top" style="height: 100px;width: 150px;" src="/media/category/logogo.jpg"
                             alt="логотип">
                    {% endif %}
                </div>
                <div class="col">
                    <div class="card-body">
                        <h5 class="card-title">{{ view.object.name }}</h5>
                        <p class="card-text">{{ view.object.description }}</p>
                    </div>
                </div>
                <div class="col mt-2">
                    <p><a href="{% url 'category:cat-crib-create' view.object.pk %}"
                          class="btn btn-primary">добавить</a></p>
                    <p><a href="{% url 'category:update' view.object.pk %}" class="btn btn-primary">изменить</a></p>
                    <p><a href="{% url 'category:delete' view.object.pk %}" class="btn btn-primary">удалить</a></p>
                </div>
            </div>
        </div>
    </div>
    <hr>

    <div class="row mt-1 ml-1 mr-1">
        {% if object_list %}
            {% for item in object_list %}
                <div class="col-4 mb-2">
                    <div class="card">
                        <div class="row g-0 ml-1 mb-1">
                            <div class="col-md-3 align-self-center">
                                <a href="{% url 'category:crib-detail' item.pk %}"
                                   class="btn btn-primary">{{ item.name }}</a>
                            </div>
                            <div class="col-md-9">
                                <div class="card-body">
                                    <p class="card-text">{{ item.description|slice:15 }}...</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="card-body">
                <p class="card-text">не найдено ни одной шпаргалки данной категории</p>
            </div>
        {% endif %}
    </div>
    <hr>

{% endblock %}